cgsite/config/routes.rb
Rails.application.routes.draw do

  resources :livros
  get 'welcome/index'

  root 'welcome#index'

  get '/divulgation' => 'welcome#divulgation'

  resources :users
  get 'welcome/index'

  root 'welcome#index'
end

cgsite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cgsite/app/models/livro.rb
class Livro < ApplicationRecord
  validates :nome_autor, presence: true

  validates :sobrenome_autor, presence:true

  validates :registro, presence:true

  validates :titulo, presence: true

  validates :cdu, presence: true

  validates :idioma_livro, presence: true

  validates :nome_serie, presence: true

  validates :volume_serie, presence: true, numericality: {greater_than: 0}

  validates :editora, presence: true

  validates :edicao, presence: true, numericality: {greater_than: 0}

  validates :isbn, presence: true
 
  validates :origem_aquisicao, presence: true
end

cgsite/app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

cgsite/app/models/user.rb
class User < ApplicationRecord
  has_many :phones
  accepts_nested_attributes_for :phones
end

cgsite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cgsite/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  def index
    @livros = Livro.all
  end

  def show
  end

  def new
    @livro = Livro.new
  end

  def edit
  end

  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:nome_autor, :sobrenome_autor, :registro, :titulo, :cdu, :idioma_livro, :nome_serie, :volume_serie, :editora, :ano, :edicao, :isbn, :data_aquisicao, :origem_aquisicao, :classificacao_etaria, :renovavel, :link_download)
    end
end
 

cgsite/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.account_status = false;

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :address, :phone, :cpf, :birthday, :student_grade, :student_shift, :user_type, :account_status, :lib_employee_id)
    end
end

cgsite/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

cgsite/app/helpers/application_helper.rb
module ApplicationHelper
end

cgsite/app/helpers/livros_helper.rb
module LivrosHelper
end

cgsite/app/helpers/users_helper.rb
module UsersHelper
end

cgsite/app/helpers/welcome_helper.rb
module WelcomeHelper
end

cgsite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca CG</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/assets/javascripts/materialize.min.js"></script>
    <%= stylesheet_link_tag("style") %>
    <%= stylesheet_link_tag("materialize") %>
    <%= stylesheet_link_tag("materialize.min") %>
    <%= javascript_tag("init") %>
    <%= javascript_tag("materialize") %>
  </head>

  <body>
    <nav class="teal lighten-1" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="/" class="brand-logo"><i class="material-icons">book</i>BCG</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="/">Log In</a></li>
          <li><a href="/">Sobre</a></li>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <li><a href="/">Log In</a></li>
          <li><a href="/">Sobre</a></li>
        </ul>
        <a href="/" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

cgsite/app/views/livros/_form.html.erb
<%= form_with(model: livro, local: true) do |form| %>
  <% if livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="field">
      <h6> Nome do autor do livro:</h6>
        <%= form.label :nome_autor %>
        <%= form.text_field :nome_autor, id: :livro_nome_autor %>
      </div>
    </div>
  </div>

  <div class="field">
    <h6> Sobrenome do autor do livro:</h6>
    <%= form.label :sobrenome_autor %>
    <%= form.text_field :sobrenome_autor, id: :livro_sobrenome_autor %>
  </div>

  <div class="field">
  <h6> Registro do livro:</h6>
    <%= form.label :registro %>
    <%= form.number_field :registro, id: :livro_registro %>
  </div>

  <div class="field">
    <h6> Título do livro:</h6>
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :livro_titulo %>
  </div>

  <div class="field">
  <h6> CDU do livro:</h6>
    <%= form.label :cdu %>
    <%= form.number_field :cdu, id: :livro_cdu %>
  </div>

  <div class="field">
    <h6> Idioma do livro:</h6>
    <%= form.label :idioma_livro %>
    <%= form.text_field :idioma_livro, id: :livro_idioma_livro %>
  </div>

  <div class="field">
    <h6> Serie ou coleção do livro:</h6>
    <%= form.label :nome_serie %>
    <%= form.text_field :nome_serie, id: :livro_nome_serie %>
  </div>

  <div class="field">
  <h6> Volume da série ou coleção livro:</h6>
    <%= form.label :volume_serie %>
    <%= form.number_field :volume_serie, id: :livro_volume_serie %>
  </div>

  <div class="field">
    <h6> Editora do livro:</h6>
    <%= form.label :editora %>
    <%= form.text_field :editora, id: :livro_editora %>
  </div>

  <div class="field">
    <h6> Ano de publicação:</h6>
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :livro_ano %>
  </div>

  <div class="field">
    <h6> Edição do livro:</h6>
    <%= form.label :edicao %>
    <%= form.number_field :edicao, id: :livro_edicao %>
  </div>

  <div class="field">
    <h6> ISBN do livro:</h6>
    <%= form.label :isbn %>
    <%= form.number_field :isbn, id: :livro_isbn %>
  </div>

  <div class="field">
    <h6> Data de aquisição do livro:</h6>
     <label for="data_aquisicao" class="active">Data</label>
   <input placeholder="Data de aquisição do Livro" id="data_aquisicao" type="date" class="validate">

  </div>

  <div class="field">
    <h6> Origem de aquisição:</h6>
    <%= form.label :origem_aquisicao %>
    <%= form.text_area :origem_aquisicao, id: :livro_origem_aquisicao %>
  </div>

  <div class="field">
  <br>
  <h6> O livro possui classificação livre?</h6>
   <form action="#">
    <p>
      <input name="group1" type="radio" id="livre" />
      <label for="livre">Sim</label>
    </p>
    <p>
      <input name="group1" type="radio" id="nlivre" />
      <label for="nlivre">Não</label>
    </p>
    </form>
  </div>

  <div class="field">
    <br><br>
    <h6> O livro é renovável?</h6>
    <form action="#">
    <p>
      <input name="group1" type="radio" id="renovavel" />
      <label for="renovavel">Sim</label>
    </p>
    <p>
      <input name="group1" type="radio" id="nrenovavel" />
      <label for="nrenovavel">Não</label>
    </p>
    </form>
  </div>

  <div class="field">
    <br> <br>
    <h6> Link de download do livro:</h6>
    <%= form.label :link_download %>
    <%= form.text_area :link_download, id: :livro_link_download do %>
      <label>Origem Aquisição</label>
    <% end %>
  </div>
  <br>
  <hr>
  <br>
  <div class="actions btn waves-effect waves-light teal lighten-1">
    <%= form.submit %><i class="material-icons left">save</i>
  </div>
<% end %>

cgsite/app/views/livros/edit.html.erb
<div class="section no-pad-bot">
  <div class="container">
    <br><br>
    <div class="card teal lighten-1">
      <br>
      <h1 class="header center white-text">Editar Livro</h1>
      <br>
    </div>
    <br>
    <%= render 'form', livro: @livro %>
    <div style="float: right;">
      <%= link_to 'Mostrar', @livro, class: "btn waves-effect waves-light green lighten-1 white-text" %>
      <%= link_to 'Voltar', livros_path, class: "btn waves-effect waves-light red white-text" %>
    </div>
    <br><br>
  </div>
</div>

cgsite/app/views/livros/index.html.erb
<style>
tbody {
  border: 1px solid black
  border-left-style: hidden;
  border-top-style: hidden;
  border-right-style: hidden;
}
</style>

<p id="notice"><%= notice %></p>
<div class="container">
  <h1 class="card teal lighten-1 white-text center">Livros</h1>

  <table>
    <thead>
      <tr>
        <th>Nome Autor</th>
        <th>Sobrenome Autor</th>
        <th>Registro</th>
        <th>Título</th>
        <th>CDU</th>
        <th>Idioma</th>
        <th>Nome da Série</th>
        <th>Volume Série</th>
        <th>Editora</th>
        <th>Ano</th>
        <th>Edição</th>
        <th>ISBN</th>
        <th>Data de Aquisição</th>
        <th>Origem de Aquisição</th>
        <th>Classificação Etária</th>
        <th>Renovável?</th>
        <th>Link Download</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @livros.each do |livro| %>
        <tr>
          <td><%= livro.nome_autor %></td>
          <td><%= livro.sobrenome_autor %></td>
          <td><%= livro.registro %></td>
          <td><%= livro.titulo %></td>
          <td><%= livro.cdu %></td>
          <td><%= livro.idioma_livro %></td>
          <td><%= livro.nome_serie %></td>
          <td><%= livro.volume_serie %></td>
          <td><%= livro.editora %></td>
          <td><%= livro.ano %></td>
          <td><%= livro.edicao %></td>
          <td><%= livro.isbn %></td>
          <td><%= livro.data_aquisicao %></td>
          <td><%= livro.origem_aquisicao %></td>
          <td><%= livro.classificacao_etaria %></td>
          <td><%= livro.renovavel %></td>
          <td><%= livro.link_download %></td>
          <td><%= link_to livro_path(livro), class: "btn waves-effect waves-light green lighten-1 white-text" do %>
            <i class="material-icons">info_outline</i>
          <% end %>
          <%= link_to edit_livro_path(livro), class: "btn waves-effect waves-light yellow lighten-2 white-text" do %>
            <i class="material-icons">create</i>
          <% end %>
          <%= link_to livro_path(livro), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn waves-effect waves-light red white-text" do%>
            <i class="material-icons">delete</i>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <br>
  <div style="float: right;">
    <%= link_to new_livro_path, style: "color: white", class: "button btn waves-effect waves-light teal lighten-1 white-text" do %>
      Novo Livro
      <i class="material-icons left">add</i>
    <% end %>
  </div>
</div>

cgsite/app/views/livros/new.html.erb
<div class="section no-pad-bot">
  <div class="container">
    <br><br>
    <div class="card teal lighten-1">
      <br>
      <h1 class="header center white-text">Novo Livro</h1>
      <br>
    </div>
  </div>
  <br>
  <div class="container">
    <%= render 'form', livro: @livro %>
    <a style="float: right" href="/livros" id="download-button" class="btn waves-effect waves-light teal lighten-1"><i class="material-icons left">undo</i> Voltar</a>
  </div>
  <br>
  <br>
</div>

cgsite/app/views/livros/show.html.erb
<div class="section no-pad-bot">
  <div class="container">
    <br><br>
    <div class="card teal lighten-1">
      <br>
      <h1 class="header center white-text">Livro</h1>
      <br>
    </div>
    <br>
    <div class="row">
      <div class="col s12 m12">
        <div class="card white">
          <div class="card-content">
            <p>
              <strong>Nome autor:</strong>
              <%= @livro.nome_autor %>
            </p>

            <p>
              <strong>Sobrenome autor:</strong>
              <%= @livro.sobrenome_autor %>
            </p>

            <p>
              <strong>Registro:</strong>
              <%= @livro.registro %>
            </p>

            <p>
              <strong>Titulo:</strong>
              <%= @livro.titulo %>
            </p>

            <p>
              <strong>Cdu:</strong>
              <%= @livro.cdu %>
            </p>

            <p>
              <strong>Idioma livro:</strong>
              <%= @livro.idioma_livro %>
            </p>

            <p>
              <strong>Nome serie:</strong>
              <%= @livro.nome_serie %>
            </p>

            <p>
              <strong>Volume serie:</strong>
              <%= @livro.volume_serie %>
            </p>

            <p>
              <strong>Editora:</strong>
              <%= @livro.editora %>
            </p>

            <p>
              <strong>Ano:</strong>
              <%= @livro.ano %>
            </p>

            <p>
              <strong>Edicao:</strong>
              <%= @livro.edicao %>
            </p>

            <p>
              <strong>Isbn:</strong>
              <%= @livro.isbn %>
            </p>

            <p>
              <strong>Data aquisicao:</strong>
              <%= @livro.data_aquisicao %>
            </p>

            <p>
              <strong>Origem aquisicao:</strong>
              <%= @livro.origem_aquisicao %>
            </p>

            <p>
              <strong>Classificacao etaria:</strong>
              <%= @livro.classificacao_etaria %>
            </p>

            <p>
              <strong>Renovavel:</strong>
              <%= @livro.renovavel %>
            </p>

            <p>
              <strong>Link download:</strong>
              <%= @livro.link_download %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div style="float: right;">
      <%= link_to 'Editar', edit_livro_path(@livro), class: "btn waves-effect waves-light yellow lighten-2 white-text" %>
      <%= link_to 'Voltar', livros_path, class: "btn waves-effect waves-light teal lighten-1 white-text" %>
    </div>
    <br><br>
  </div>
</div>

cgsite/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :user_type %>
    <%= form.number_field :user_type, id: :user_user_type %>
  </div> -->

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :user_address %>
  </div>


  <%= form.fields_for :phones do |ff| %>
    <div class="field">
      <%= form.label "Phone" %>
      <!-- <%= form.text_field :phone, id: :user_phone %> -->
      <%= ff.text_field :num_phone, id: 'num_phone'%>
    </div>
  <% end %>

  <% if !@user.id %>
  <%= form.fields_for :phones do |ff| %>
    <div class="field">
      <%= form.label "Phone" %>
      <!-- <%= form.text_field :phone, id: :user_phone %> -->
      <%= ff.text_field :num_phone, id: 'num_phone'%>
    </div>
  <% end %>
  <% end %>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :user_cpf %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :user_birthday %>
  </div>

  <div class="field">
    <%= form.label :student_grade %>
    <%= form.text_field :student_grade, id: :user_student_grade %>
  </div>

  <div class="field">
    <%= form.label :student_shift %>
    <%= form.text_field :student_shift, id: :user_student_shift %>
  </div>

  <div class="field">
    <%= form.label :account_status %>
    <%= form.check_box :account_status, id: :user_account_status %>
  </div>

  <div class="field">
    <%= form.label :lib_employee_id %>
    <%= form.text_field :lib_employee_id, id: :user_lib_employee_id %>
  </div>

  <br>
  <hr>
  <br>
  <div class="actions btn waves-effect waves-light teal lighten-1">
    <%= form.submit %><i class="material-icons left">save</i>
  </div>
<% end %>

cgsite/app/views/users/edit.html.erb
<div class="section no-pad-bot">
	<div class="container">
    	<br><br>
    	<div class="card teal lighten-1">
     	 <br>
      	<h1 class="header center white-text">Editar Usuário</h1>
      	<br>
    	</div>
  	</div>
  	<br>
	<div class="container">

<%= render 'form', user: @user %>

<div class="actions btn waves-effect waves-light teal lighten-1">
<%= link_to 'Mostrar', @user %>
</div>

<a style="float: right" href="/users" id="download-button" class="btn waves-effect waves-light teal lighten-1"><i class="material-icons left">undo</i> Voltar</a>

  <br>
  <br>
</div>

cgsite/app/views/users/index.html.erb
<div class="section no-pad-bot">
  <div class="container">
      <br><br>
      <div class="card teal lighten-1">
       <br>
        <h1 class="header center white-text">Lista de Usuários</h1>
        <br>
      </div>
    </div>
    <br>
  <div class="container">
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>ID</th>
      <th>E-mail</th>
      <th>CPF</th>
      <th>Série</th>
      <th>Turno</th>
      <th>Tipo de Usuário</th>
      <th>Estado da conta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.cpf %></td>
        <td><%= user.student_grade %></td>
        <td><%= user.student_shift %></td>
        <td><%= user.user_type %></td>
        <td><%= user.account_status %></td>
        <td><%= link_to 'Mostrar', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="actions btn waves-effect waves-light teal lighten-1">
  <%= link_to 'Novo', new_user_path %>
</div>


  <br>
  <br>
</div>

cgsite/app/views/users/new.html.erb
<div class="section no-pad-bot">
	<div class="container">
    	<br><br>
    	<div class="card teal lighten-1">
     	 <br>
      	<h1 class="header center white-text">Formulário de Cadastro</h1>
      	<br>
    	</div>
  	</div>
  	<br>
	<div class="container">

	<%= render 'form', user: @user %>

	<a style="float: right" href="/users" id="download-button" class="btn waves-effect waves-light teal lighten-1"><i class="material-icons left">undo</i> Voltar</a>
	</div>
  <br>
  <br>
</div>

cgsite/app/views/users/show.html.erb
<div class="section no-pad-bot">
  <div class="container">
      <br><br>
      <div class="card teal lighten-1">
       <br>
        <h1 class="header center white-text">Informações do Usuário</h1>
        <br>
      </div>
    </div>
    <br>
  <div class="container">

<p id="notice"><%= notice %></p>

<p>
  <h5>Nome:</h5>
  <%= @user.name %>
</p>

<p>
  <h5>Número do Usuário:</h5>
  <%= @user.id %>
</p>

<p>
  <h5>E-mail:</h5>
  <%= @user.email %>
</p>

<p>
  <h5>Endereço:</h5>
  <%= @user.address %>
</p>

<p>
  <h5>Telefone:</h5>
  <% @user.phones.each do |p| %>
    <%= p.num_phone %>
  <% end %>
</p>

<p>
  <h5>CPF:</h5>
  <%= @user.cpf %>
</p>

<p>
  <h5>Data de Nascimento:</h5>
  <%= @user.birthday %>
</p>

<p>
  <h5>Série:</h5>
  <%= @user.student_grade %>
</p>

<p>
  <h5>Turno:</h5>
  <%= @user.student_shift %>
</p>

<p>
  <h5>Tipo de usário:</h5>
  <%= @user.user_type %>
</p>

<p>
  <h5>Estado da conta:</h5>
  <%= @user.account_status %>
</p>

<p>
  <h5>Matrícula da biblioteca:</h5>
  <%= @user.lib_employee_id %>
</p>

<p>
  <h5>Data de cadastro:</h5>
  <%= @user.created_at %>
</p>

<div class="actions btn waves-effect waves-light teal lighten-1">
<%= link_to 'Editar', edit_user_path(@user) %>
</div>

<div style="float: right" href="/users" id="download-button" class="btn waves-effect waves-light teal lighten-1">
<%= link_to 'Voltar', users_path %>
<i class="material-icons left">undo</i>
</div>

  <br>
  <br>
</div>

cgsite/app/views/welcome/divulgation.html.erb
<div id="background_welcome">
  <div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
  <div class="container">
    <br><br>
    <h1 class="header center teal-text text-lighten-1">Biblioteca do CG</h1>
    <div class="row center">
      <h5 class="teal-text header col s12">Você também pode ser um escritor! Basta entrar em contato com a gente e nós iremos lhe informar como isso é possível. Estes são alguns dos nossos projetos.</h5>
    </div>
    <div class="row center">
      <a id="negrito" href="https://www.facebook.com/mentecapta.castro.alves/" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Projeto Mente Capta</a>
      <a id="negrito" href="https://www.facebook.com/literato.castro.alves/" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Projeto Literato</a>
    </div>
    <br><br>
  </div>
  </div>
  </div>
  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Centro de Ensino Médio 01 do Gama</h5>
          <p class="white-text text-lighten-4">O Centro de Ensino Médio 01 do gama também conhecido como CG é uma escola de ensino médio que está localizado no Setor Leste do Gama, uma cidade satélite do Distrito Federal. Conta com uma ampla estrutura de ensino com todos os meios básicos de uma escola poder oferecer, é uma das escolas privilegiadas e conta como laboratório de informática, física e química, além de um auditório que é usado para múltiplas funções.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Outros Links</h5>
          <ul>
            <li><a class="white-text" href="/divulgation">Veja Nossos Projetos</a></li>
            <li><a class="white-text" href="https://www.facebook.com/soecem01gama/?hc_ref=PAGES_TIMELINE&fref=nf">Nosso Facebook</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Contatos</h5>
          <ul>
            <li><a class="white-text" href="#!">Marília</a></li>
            <li><a class="white-text" href="#!">Lindalva</a></li>
            <li><a class="white-text" href="#!">Damaris</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Criado por <a class="brown-text text-lighten-3">Grupo 09 - DiLuJoMa</a>
      </div>
    </div>
  </footer>
</div>